# Generated by Django 5.2.8 on 2025-11-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='billable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
