# Generated by Django 5.2.8 on 2025-11-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.purchaseorder',),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase Order Line',
                'verbose_name_plural': 'Purchase Order Lines',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.purchaseorderline',),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.salesorder',),
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
            ],
            options={
                'verbose_name': 'Sales Order Line',
                'verbose_name_plural': 'Sales Order Lines',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.salesorderline',),
        ),
    ]
