# Generated by Django 5.2.8 on 2025-11-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.product',),
        ),
    ]
